###
POST Http://localhost:9000/Api/forms HTTP/1.1
Content-Type: application/json

{
   "preference": 1,
    "link": "https://es.stackoverflow.com/questions/72141/obtener-el-valor-del-select-seleccionado-javascript-dom",
    "name": "Formulario de prueba",
    "icon": 4
}
  
###
GET Http://localhost:9000/Api/users HTTP/1.1

###
GET Http://localhost:9000/Api/users/6440346a0ce48e90652cef5b HTTP/1.1

### 
PUT Http://localhost:9000/Api/users/6440346a0ce48e90652cef5b  HTTP/1.1
Content-Type: application/json

{
    "name": "hola"
}


###
DELETE Http://localhost:9000/Api/users/6443374f0ce48e90652cf28f  HTTP/1.1


